### ISSUE TITLE
error: cannot access Stable

### ISSUE THREAD

**Issue by Olesya-Egorova** [skydoves/Balloon#727]
**Please complete the following information:**
- Library Version v1.6.8
 
**Describe the Bug:**

We use com.github.skydoves:balloon library. A compilation error occurs: 

```
error: cannot access Stable
  class file for androidx.compose.runtime.Stable not found
```
I guess it happens because of the library's build.gradle file contains `compileOnly()` configuration that contains `com.github.skydoves:compose-stable-marker` dependency. If we add `compileOnly("com.github.skydoves:compose-stable-marker:1.0.5")` in our project's build.gradle file then the app build will be successful.

**Expected Behavior:**

The app build is successful or `README` contains information about compile-only dependencies that are needed.

**Comment by skydoves** [comment]
Hey @Olesya-Egorova, sorry for the late response. Does your project doesn't have any dependencies on Jetpack Compose?

**Comment by Olesya-Egorova** [comment]
> Hey @Olesya-Egorova, sorry for the late response. Does your project doesn't have any dependencies on Jetpack Compose?

Hi! Yes, we don't use Jetpack Compose in our project

**Comment by skydoves** [comment]
This is very weird. My project that doesn't have any dependency on Jetpack Compose still works well with the version of balloon 1.6.9.

**Comment by Olesya-Egorova** [comment]
> I tested it with my [demo project](https://github.com/skydoves/TransformationLayout/tree/main/app) and the result is like the below:
> 
> ![Screenshot 2024-10-22 at 12 31 28 PM](https://private-user-images.githubusercontent.com/24237865/378669776-dfde31b7-d85b-4ef3-a9e5-8acd1d4a744c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjI0NjMsIm5iZiI6MTcyOTc2MjE2MywicGF0aCI6Ii8yNDIzNzg2NS8zNzg2Njk3NzYtZGZkZTMxYjctZDg1Yi00ZWYzLWE5ZTUtOGFjZDFkNGE3NDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA5MjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ODlmY2Y3YTE2ZDI0YTZiYTg4MjE1NzEyOWQ2MDVlOTRjNTRlZjU2NjhiNDBhYmNhMGM5NGYwNDk1OGUzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6dZWBmcMe5f3auEKbL7lUKtG32Zqfv7IufXa4bt4MZo)

Thaks for your example. I've created [demo project](https://github.com/Olesya-Egorova/ballon_library_build_error_example) too. It duplicates some Gradle settings and dependencies from real project. The demo project uses `Balloon.Factory()` and when we use `kapt()` configuration (lib/build.gradle.kts) then error will be occurred

**Comment by skydoves** [comment]
Hey @Olesya-Egorova, thank you so much for creating the demo project. I just checked it and will resolved it on the next release. In the mean time, you can see it works well if you add the dependency below on the `lib` module:

```kotlin
compileOnly("com.github.skydoves:compose-stable-marker:1.0.5")
```

**Comment by skydoves** [comment]
Hey @Olesya-Egorova, this issue has been fixed on 1.6.10. Thank you so much for your report!

**Comment by Olesya-Egorova** [comment]
> Hey @Olesya-Egorova, this issue has been fixed on 1.6.10. Thank you so much for your report!

Thank you for quick fix!
